[project]
name = "task-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.129.0",
    "logging>=0.4.9.6",
    "pydantic>=2.12.5",
    "typing>=3.10.0.0",
    "uvicorn>=0.40.0",
]
